version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: css-kata-web
    volumes:
      - "./src:/usr/share/nginx/html"
    ports:
      - "81:80"
    tty: true